import React from 'react';

const About = () => (
  <div className="ui basic padded segment">
    <h3 className="ui header">About</h3>
    <span className="ui grey text">
      Find original, minimal poetry behind any twitter noise. Powered by artificial intelligence, tweets and haiku magic, Tweet-Ku generates experimental haikus to spark reflection and allow us to see past the twitter banter.
    </span>
    <h3 className="ui header">How?</h3>
    <span className="ui grey text">
      Tweet-ku takes any public Twitter handle. It retrieves the most recent tweets and analyzes them using natural language processing (courtesy of <a href="https://www.ibm.com/cloud/watson-natural-language-understanding" >IBM</a>) in order to categorize tweets into re-usable words and phrases. A random haiku will be generated by re-combining these words and phrases in unexpected ways.
    </span>
    <h3 className="ui header">Why?</h3>
    <span className="ui grey text">
      A haiku from your tweets might spark joy, or you might even find that you have a soul after all.
    </span>
  </div>
)

export default About;
